-- MySQL Script generated by MySQL Workbench
-- Fri Jan 18 15:55:13 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ARIS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ARIS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ARIS` DEFAULT CHARACTER SET utf8 ;
USE `ARIS` ;

-- -----------------------------------------------------
-- Table `ARIS`.`ACCOUNT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ARIS`.`ACCOUNT` ;

CREATE TABLE IF NOT EXISTS `ARIS`.`ACCOUNT` (
  `account_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `f_name` VARCHAR(50) NOT NULL,
  `l_name` VARCHAR(50) NOT NULL,
  `account_type` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`account_id`))
ENGINE = InnoDB;
ALTER TABLE ACCOUNT AUTO_INCREMENT=10000;

-- -----------------------------------------------------
-- Table `ARIS`.`REPORT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ARIS`.`REPORT` ;

CREATE TABLE IF NOT EXISTS `ARIS`.`REPORT` (
  `report_id` INT NOT NULL,
  `report_title` VARCHAR(30) NOT NULL,
  `date_created` DATE NOT NULL,
  `report_content` VARCHAR(500) NULL,
  `date_completed` DATE NULL,
  `report_status` VARCHAR(30) NOT NULL,
  `report_path` VARCHAR(500) NOT NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`report_id`, `account_id`),
  INDEX `fk_REPORT_ACCOUNT1_idx` (`account_id` ASC),
  CONSTRAINT `fk_REPORT_ACCOUNT1`
    FOREIGN KEY (`account_id`)
    REFERENCES `ARIS`.`ACCOUNT` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ARIS`.`NOTIFICATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ARIS`.`NOTIFICATION` ;

CREATE TABLE IF NOT EXISTS `ARIS`.`NOTIFICATION` (
  `notification_id` INT NOT NULL,
  `order_id` INT NULL,
  `notification_type` VARCHAR(20) NOT NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`notification_id`, `account_id`),
  INDEX `fk_NOTIFICATION_ACCOUNT1_idx` (`account_id` ASC),
  CONSTRAINT `fk_NOTIFICATION_ACCOUNT1`
    FOREIGN KEY (`account_id`)
    REFERENCES `ARIS`.`ACCOUNT` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ARIS`.`PRINTER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ARIS`.`PRINTER` ;

CREATE TABLE IF NOT EXISTS `ARIS`.`PRINTER` (
  `printer_id` INT NOT NULL,
  `printer_size` VARCHAR(20) NOT NULL,
  `printer_status` VARCHAR(20) NOT NULL,
  `printer_name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`printer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ARIS`.`FILE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ARIS`.`FILE` ;

CREATE TABLE IF NOT EXISTS `ARIS`.`FILE` (
  `file_name` VARCHAR(30) NOT NULL,
  `file_path` VARCHAR(500) NOT NULL,
  `file_size` INT NULL,
  `file_type` VARCHAR(5) NULL,
  `date_submitted` DATE NOT NULL,
  `date_archived` DATE NULL,
  PRIMARY KEY (`file_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ARIS`.`ORDER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ARIS`.`ORDER` ;

CREATE TABLE IF NOT EXISTS `ARIS`.`ORDER` (
  `order_id` INT NOT NULL,
  `cost` DOUBLE NOT NULL,
  `order_date` DATE NOT NULL,
  `print_date` DATE NULL,
  `order_status` VARCHAR(20) NOT NULL,
  `printer_id` INT NOT NULL,
  `material_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  `file_name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`order_id`, `account_id`, `printer_id`, `file_name`),
  INDEX `fk_ORDER_ACCOUNT1_idx` (`account_id` ASC) ,
  INDEX `fk_ORDER_PRINTER1_idx` (`printer_id` ASC) ,
  INDEX `fk_ORDER_FILE1_idx` (`file_name` ASC) ,
  CONSTRAINT `fk_ORDER_ACCOUNT1`
    FOREIGN KEY (`account_id`)
    REFERENCES `ARIS`.`ACCOUNT` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDER_PRINTER1`
    FOREIGN KEY (`printer_id`)
    REFERENCES `ARIS`.`PRINTER` (`printer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDER_FILE1`
    FOREIGN KEY (`file_name`)
    REFERENCES `ARIS`.`FILE` (`file_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ARIS`.`ORDER_QUEUE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ARIS`.`ORDER_QUEUE` ;

CREATE TABLE IF NOT EXISTS `ARIS`.`ORDER_QUEUE` (
  `position` INT NOT NULL,
  `order_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`order_id`, `account_id`),
  CONSTRAINT `fk_ORDER_QUEUE_ORDER1`
    FOREIGN KEY (`order_id` , `account_id`)
    REFERENCES `ARIS`.`ORDER` (`order_id` , `account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ARIS`.`MATERIAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ARIS`.`MATERIAL` ;

CREATE TABLE IF NOT EXISTS `ARIS`.`MATERIAL` (
  `material_name` VARCHAR(30) NULL,
  `material_description` VARCHAR(500) NULL,
  `material_id` INT NOT NULL,
  PRIMARY KEY (`material_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ARIS`.`PRINTER_MATERIAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ARIS`.`PRINTER_MATERIAL` ;

CREATE TABLE IF NOT EXISTS `ARIS`.`PRINTER_MATERIAL` (
  `printer_id` INT NOT NULL,
  `material_id` INT NOT NULL,
  PRIMARY KEY (`printer_id`, `material_id`),
  INDEX `fk_PRINTER_MATERIAL_MATERIAL1_idx` (`material_id` ASC),
  CONSTRAINT `fk_PRINTER_MATERIAL_PRINTER1`
    FOREIGN KEY (`printer_id`)
    REFERENCES `ARIS`.`PRINTER` (`printer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRINTER_MATERIAL_MATERIAL1`
    FOREIGN KEY (`material_id`)
    REFERENCES `ARIS`.`MATERIAL` (`material_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ARIS`.`NOTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ARIS`.`NOTE` ;

CREATE TABLE IF NOT EXISTS `ARIS`.`NOTE` (
  `note_id` INT NOT NULL AUTO_INCREMENT,
  `date_created` DATE NOT NULL,
  `object_id` INT NOT NULL,
  `note_content` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`note_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
